### ISSUE TITLE
Use WP_Serve_File class to serve the registrar

### ISSUE THREAD

**Issue by marco-c** [mozilla/wp-sw-manager#4]
https://github.com/marco-c/WP_Serve_File

**Comment by delapuente** [comment]
Better, let's use WP_Serve_File to serve the registrar only. This does not affect the dynamic characteristics of the collaborative service worker keeping the API simple enough for consumers and without alterations but reduce the same amount of overhead as the SW is already cached for a day by spec and new registrations does not ping the network for new versions ([step 5.3 of register algortihm](https://slightlyoff.github.io/ServiceWorker/spec/service_worker/index.html#register-algorithm)).

**Comment by marco-c** [comment]
Fixed by #7.
